accounts/urls.py
from django.urls import path,include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/',views.login_view,name='login'),
    path('',include('django.contrib.auth.urls')),
    path('register',views.register_view,name='register'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('',views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from orders.views import paymenthandler

urlpatterns = [
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('paymenthandler/', paymenthandler, name='paymenthandler'),
    path('d465091e-8335-412e-892f-9c6858d92462/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('feedback/', views.feedback, name='feedback'),
    path("contactus/", views.contact_us, name="contact_us"),
    path("payment_methods", views.payment_methods, name="payment_methods"),
    path("delivery", views.delivery, name="delivery"),
    path("return_exch", views.return_exch, name="return_exch"),
    path('search/', views.post_search, name='post_search'),
    path('shop/', views.product_list, name='product_list'),
    path('product/review/', views.review_form,name='product_review'),
    path('<int:id>/<slug:slug>/', views.product_detail,name='product_detail'),
    path('<slug:category_slug>/', views.product_list,name='product_list_by_category'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator,MinValueValidator

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,unique=True)

    def get_absolute_url(self):
        return reverse("shop:product_list_by_category", args= [self.slug])
    

    class Meta: 
        ordering = ['name',]
        indexes = [
            models.Index(fields=['name']),
        ]

        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
        
    def count(self):
        return Product.objects.filter(category=self).count()

class Product(models.Model):
    category = models.ForeignKey(Category,on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='products/%Y/%m/%d/')
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    def get_absolute_url(self):
        return reverse("shop:product_detail", args=[self.id,self.slug])

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id','slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]
    
    def __str__(self):
        return self.name
    

class ProductImage(models.Model):
    name = models.CharField(max_length=30)
    product = models.ForeignKey(Product,related_name='images',on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/%Y/%m/%d/')

    def __str__(self):
        return self.name


class ProductReview(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE,related_name='reviews')
    created = models.DateTimeField(auto_now_add=True)
    body = models.TextField(null=False)
    rating = models.IntegerField(choices=[
        (1,'Terrible'),
        (2,'poor'),
        (3,'Average'),
        (4,'Good'),
        (5,'Excellent'),
    ],default=5,
    validators=[MaxValueValidator(5),MinValueValidator(1)])

    class Meta:
        ordering = ['-created']


class SiteReviewModel(models.Model):

    created = models.DateTimeField(auto_now_add=True)
    body = models.TextField(null=False)
    rating = models.IntegerField(choices=[
        (1,'Terrible'),
        (2,'poor'),
        (3,'Average'),
        (4,'Good'),
        (5,'Excellent'),
    ],default=5,
    validators=[MaxValueValidator(5),MinValueValidator(1)])

    class Meta:
        ordering = ['-created']

shop/forms.py
from django import forms
from .models import ProductReview,SiteReviewModel

class ReviewForm(forms.ModelForm):

    class Meta:
        model = ProductReview
        fields = ['product','body','rating']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        # Hide the 'product' field by using the HiddenInput widget
        self.fields['product'].widget = forms.HiddenInput()
    
class SiteReviewForm(forms.ModelForm):
    
    class Meta:
        model = SiteReviewModel
        fields = ['body','rating']
    
    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['body'].widget.attrs.update({'class': 'mx-3'})

shop/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Product,Category,SiteReviewModel
from cart.forms import CartAddProductForm
from django.contrib.postgres.search import SearchRank,SearchVector,SearchQuery
from .forms import ReviewForm,SiteReviewForm
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.core.paginator import Paginator
# Create your views here.

def product_list(request,category_slug=None):
    page_number = request.GET.get('page', 1)
    category = None
    if category_slug:
        category = get_object_or_404(Category,slug=category_slug)
        products = Product.objects.filter(category=category)
    else:
        products = Product.objects.filter(available=True)
    
    total_product_count = Product.objects.all().count()
    paginator = Paginator(products,4)
    categories = Category.objects.all()
    cart_product_form = CartAddProductForm()
    products = paginator.get_page(page_number)

    return render(request,'shop/product/list.html',
                            {'category': category,
                            'categories': categories,
                            'products': products,
                            'total_product_count': total_product_count,
                            'page_product_count': len(products),
                            'cart_product_form': cart_product_form})

def product_detail(request, id, slug):
    product = get_object_or_404(Product,
    id=id,
    slug=slug)
    form = ReviewForm({"product":product,
                       "rating":(5,'Excellent'),})
    return render(request,
    'shop/product/detail.html',
    {'product': product,
    'form':form})


def home(request):
   try:
        products = Product.objects.all()[:6]
   except IndexError:
        products = Product.objects.all()

   return render(request,'shop/home.html',{'products':products})


def post_search(request):
    query = None
    results = []
    
    if 'search' in request.GET:
        query = request.GET.get('search')
        print(query)
        search_vector = SearchVector('name')
        search_query = SearchQuery(query)

        results = Product.objects.annotate(
            search=search_vector,
            rank=SearchRank(search_vector, search_query)
        ).filter(search=search_query).order_by('-rank')
        print(results)
    return render(request, 'shop/search.html', {
        'query': query,
        'results': results,
    })

@require_POST
def review_form(request):
    form = ReviewForm(request.POST)
    referring_url = request.META.get('HTTP_REFERER', '/')
    if form.is_valid():
        form.save()
        messages.success(request,"review submitted")
    else:
        messages.error(request,'review not valid')
    return redirect(referring_url)

def feedback(request):

    reviews_count = SiteReviewModel.objects.all().count()
    if reviews_count>5:
        reviews = SiteReviewModel.objects.all()[:5]
    else:
        reviews = SiteReviewModel.objects.all()
    if request.method == "POST":
        form = SiteReviewForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Feedback submitted')
            return redirect(request.META.get('HTTP_REFERER', '/'))

        else:
            messages.error(request,'Failed to submit the Feedback')
            return render(request,'shop/feedback.html',{'form':form,
                                                'reviews':reviews})
    form = SiteReviewForm()
    return render(request,'shop/feedback.html',{'form':form,
                                                'reviews':reviews})

def contact_us(requests):
    return render(requests, 'shop/contact_us.html')

def payment_methods(requests):
    return render(requests, 'shop/payment_methods.html')


def delivery(requests):
    return render(requests, 'shop/delivery.html')

def return_exch(requests):
    return render(requests, 'shop/return_exch.html')

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Male_Fashion Template">
    <meta name="keywords" content="Male_Fashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} {% endblock title %}</title>
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/x-icon">

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&display=swap"
    rel="stylesheet">

    <!-- Css Styles -->
     
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>

<body>
    

<!-- Page Preloder -->
<div id="preloder">
    <div class="loader"></div>
</div>

    <!-- Offcanvas Menu Begin -->
    <div class="offcanvas-menu-overlay"></div>
    <div class="offcanvas-menu-wrapper">
        <div class="offcanvas__option">
            <div class="offcanvas__links">
                {% if request.user.is_authenticated %}
                <form class="d-inline" action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" style="background-color:rgb(255, 255, 255);border: none;" class="btn">Logout</button>
                </form>
                {% else %}
                <a href="{% url 'accounts:login' %}">Sign in</a>
                {% endif %}
            </div>
        </div>
        <div class="offcanvas__nav__option">
            <a href="#" class="search-switch"><img src="{% static 'img/icon/search.png' %}" alt=""></a>
            <a href="#"><img src="{% static 'img/icon/heart.png' %}" alt=""></a>
            <a href="#"><img src="{% static 'img/icon/cart.png' %}" alt=""> <span>{{ cart|length }}</span></a>
            <div class="price">₹{{ cart.get_total_price }}</div>
        </div>
        <div id="mobile-menu-wrap"></div>
    </div>
    <!-- Offcanvas Menu End -->

<!-- Header Section Begin -->
<header class="header">
    <div class="header__top">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-7">
                </div>
                <div class="col-lg-6 col-md-5">
                    <div class="header__top__right">
                        <div class="header__top__links">
                            {% if user.is_authenticated %}
                            <form class="d-inline" action="{% url 'accounts:logout' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" style="background-color: #0f1011;border: none;" class="btn btn-dark">Logout</button>
                            </form>
                            {% else %}
                            <a href="{% url 'accounts:login' %}">Sign in</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3">
                <div class="header__logo">
                    <a class="logo" href="/"><img src="{% static 'img/logo.jpeg' %}" alt=""></a>
                </div>
            </div>
            <div class="mt-4 col-lg-6 col-md-6">
                <nav class="header__menu mobile-menu">
                    <ul>
                        <li class="active"><a href="/">Home</a></li>
                        <li><a href="/shop">Shop</a></li>
                        <li><a href="/cart">Shopping Cart</a></li>
                        <li><a href="/orders/create">Check Out</a></li>
                        {% comment %} <li><a href="/contact">Contacts Us</a></li> {% endcomment %}
                        {% comment %} <li><a href="/blog">Blog</a></li> {% endcomment %}
                    </ul>
                </nav>
            </div>
            <div class="mt-4 col-lg-3 col-md-3">
                <div class="header__nav__option">
                    <a href="#" class="search-switch"><img src="{% static 'img/icon/search.png' %}" alt=""></a>
                    <a href="#"><img src="{% static 'img/icon/heart.png' %}" alt=""></a>
                    <a href="#"><img src="{% static 'img/icon/cart.png' %}" alt=""> <span>{{ cart|length }}</span></a>
                    <div class="price">₹{{ cart.get_total_price }}</div>
                </div>
            </div>
        </div>
        <div class="canvas__open mt-4 mr-4"><i class="fa fa-bars"></i></div>
    </div>
</header>
<!-- Header Section End -->

    {% block content %}
    {% block message %}
    {% if messages %}
    <ul id="messages_box" class="messages">
        {% for message in messages %}
            {% if message.tags == 'error' %}
              <div class="alert alert-danger alert-dismissible fade show custom-alert" role="alert">
                {{message}}
                <strong class="killAlert" style="float: right;cursor: pointer;">&times;</strong>
              </div>
            {% else %}
              <div class="alert alert-{{message.tags}} alert-dismissible fade show custom-alert" role="alert">
                {{message}}
                <strong class="killAlert" style="float: right;cursor: pointer;">&times;</strong>
              </div>
            {% endif %}
        {% endfor %}
    </ul>
    {% endif %}
  {% endblock message %}

    {% endblock content %}

    <!-- Footer Section Begin -->
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer__about">
                        <div class="footer__logo">
                            <a href="#"><img src="{% static 'img/footer-logo.jpeg' %}" alt=""></a>
                        </div>
                        <p>The customer is at the heart of our unique business model, which includes design.</p>
                        <a href="#"><img src="{% static 'img/payment.png' %}" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-2 col-md-3 col-sm-6">
                    <div class="footer__widget">
                        <h6>Shopping</h6>
                        <ul>
                            <li><a href="{% url 'shop:contact_us' %}">Contact Us</a></li>
                            <li><a href="{% url 'shop:payment_methods' %}">Payment Methods</a></li>
                            <li><a href="{% url 'shop:delivery' %}">Delivery</a></li>
                            <li><a href="{% url 'shop:return_exch' %}">Return & Exchanges</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 offset-lg-1 col-md-6 col-sm-6">
                    <div class="footer__widget">
                        <h6>NewLetter</h6>
                        <div class="footer__newslatter">
                            <p>Be the first to know about new arrivals, look books, sales & promos!</p>
                            <form action="#">
                                <input type="text" placeholder="Your email">
                                <button type="submit"><span class="icon_mail_alt"></span></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="footer__copyright__text">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        <p>Copyright ©
                            <script>
                                document.write(new Date().getFullYear());
                            </script>2020
                            All rights reserved | This template is made with <i class="fa fa-heart-o"
                            aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        </p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

    <!-- Search Begin -->
    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch">+</div>
            <form class="search-model-form" method="get" action="{% url 'shop:post_search' %}">
                <input name="search" type="text" id="search-input" placeholder="Search here.....">
            </form>
        </div>
    </div>
    <!-- Search End -->

    <!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery.nicescroll.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/customjs.js' %}"></script>
</body>

</html>

shop/templates/shop/contact_us.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}Contact Us{% endblock title %}
{% block content %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Us - Footer</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: Arial, sans-serif;
        }

        .contact-container {
            max-width: 500px;
            margin: 0 auto;
            text-align: left;
        }

        .contact-container h3 {
            margin-bottom: 15px;
        }

        .contact-form input, 
        .contact-form textarea {
            width: 100%;
            padding: 10px;
            margin: 10px 0;
            border: none;
            border-radius: 5px;
        }

        .contact-form textarea {
            height: 100px;
            resize: none;
        }

        .contact-form button {
            width: 100%;
            padding: 10px;
            background-color: #ff6600;
            border: none;
            color: white;
            font-size: 16px;
            cursor: pointer;
            border-radius: 5px;
        }

        .contact-form button:hover {
            background-color: #e65c00;
        }

        @media (max-width: 600px) {
            .contact-container {
                width: 90%;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="contact-container">
            <h3>Contact Us</h3>
            <form class="contact-form">
                <input type="text" name="name" placeholder="Your Name" required>
                <input type="email" name="email" placeholder="Your Email" required>
                <textarea name="message" placeholder="Your Message" required></textarea>
                <button type="submit">Send Message</button>
            </form>
            <br>
        </div>
    </div>
</body>
</html>

{% endblock %}

shop/templates/shop/delivery.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}Delivery Policy{% endblock title %}
{% block content %}

<div class="container mt-5">
    <div class="policy-container mx-auto p-4 shadow-lg rounded bg-white" style="max-width: 700px;">
        <h3 class="text-center mb-4">Delivery Policy</h3>
        <p>We strive to deliver your orders as quickly as possible. Please read our delivery policy below:</p>

        <h5>1. Processing Time</h5>
        <p>Orders are typically processed within **1-2 business days** after payment confirmation.</p>

        <h5>2. Shipping Time</h5>
        <p>Standard shipping takes **5-7 business days**, while express shipping takes **2-3 business days**.</p>

        <h5>3. Delivery Charges</h5>
        <p>Delivery charges may vary based on location and order size. Free shipping is available for orders above **₹1000**.</p>

        <h5>4. Order Tracking</h5>
        <p>Once shipped, you will receive a tracking number to monitor your package in real-time.</p>

        <h5>5. Delays & Issues</h5>
        <p>If there are any delays due to unforeseen circumstances, we will notify you immediately.</p>

        <h5>6. Returns & Refunds</h5>
        <p>If you receive a damaged or incorrect product, you can request a replacement within **7 days**.</p>

        <p class="text-center mt-4"><strong>For further inquiries, please <a href="{% url 'shop:contact_us' %}">Contact Us</a>.</strong></p>
    </div>
</div>

{% endblock %}

shop/templates/shop/payment_methods.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}Payment Methods Policy{% endblock title %}
{% block content %}

<div class="container mt-5">
    <div class="policy-container mx-auto p-4 shadow-lg rounded bg-white" style="max-width: 700px;">
        <h3 class="text-center mb-4">Payment Methods Policy</h3>
        <p>We offer multiple payment methods for a seamless shopping experience. Please review our policy below:</p>

        <h5>1. Accepted Payment Methods</h5>
        <ul>
            <li><strong>Credit/Debit Cards:</strong> Visa, MasterCard, American Express, and RuPay.</li>
            <li><strong>UPI Payments:</strong> Google Pay, PhonePe, Paytm, and BHIM UPI.</li>
            <li><strong>Net Banking:</strong> Available for major Indian banks.</li>
            <li><strong>Wallet Payments:</strong> Paytm Wallet, Amazon Pay, and Mobikwik.</li>
            <li><strong>Cash on Delivery (COD):</strong> Available for select locations.</li>
        </ul>

        <h5>2. Security & Encryption</h5>
        <p>All transactions are encrypted using **SSL security** to ensure the safety of your payment information.</p>

        <h5>3. Payment Failures & Refunds</h5>
        <p>If a payment fails but the amount is deducted, it will be refunded within **5-7 business days**.</p>

        <h5>4. EMI & Installment Plans</h5>
        <p>We offer EMI options for purchases above ₹5000 on select credit cards.</p>

        <h5>5. Fraud Prevention</h5>
        <p>For security reasons, we may require additional verification for high-value transactions.</p>

        <p class="text-center mt-4"><strong>For payment-related issues, please <a href="{% url 'shop:contact_us' %}">Contact Us</a>.</strong></p>
    </div>
</div>

{% endblock %}

shop/templates/shop/return_exch.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}Return & Exchange Policy{% endblock title %}
{% block content %}

<div class="container mt-5">
    <div class="policy-container mx-auto p-4 shadow-lg rounded bg-white" style="max-width: 700px;">
        <h3 class="text-center mb-4">Return & Exchange Policy</h3>
        <p>We want you to be fully satisfied with your purchase. Please read our return and exchange policy below:</p>

        <h5>1. Return Eligibility</h5>
        <ul>
            <li>Items can be returned within **7 days** of delivery.</li>
            <li>Products must be unused, in their original packaging, and with all tags intact.</li>
            <li>Returns are not accepted for perishable items, personalized products, or hygiene-sensitive goods.</li>
        </ul>

        <h5>2. Exchange Policy</h5>
        <ul>
            <li>Exchanges are allowed for defective or incorrect products.</li>
            <li>Customers must raise an exchange request within **7 days** of receiving the order.</li>
        </ul>

        <h5>3. Refund Process</h5>
        <p>Once we receive your returned item, refunds will be processed within **5-7 business days** to your original payment method.</p>

        <h5>4. Return Shipping</h5>
        <p>Customers are responsible for return shipping costs unless the item is defective or incorrect.</p>

        <h5>5. How to Initiate a Return/Exchange</h5>
        <p>To start a return or exchange, please contact our customer support at <a href="{% url 'shop:contact_us' %}">Contact Us</a>.</p>

        <p class="text-center mt-4"><strong>For more details, please reach out to our support team.</strong></p>
    </div>
</div>

{% endblock %}